-- =========================================================
-- 기준 데이터(카테고리) + 데모 로그인 계정
-- =========================================================

ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = TRACKER;

-- 데모 로그인 계정 (아이디: testuser / 비밀번호: demo1234!)
-- TASK_CATEGORY.USER_ID가 FK로 USERS를 참조하므로 카테고리보다 먼저 넣어야 함.
-- USER_ID를 DemoDataSeeder.USER_ID("testuser")와 동일하게 맞춰서,
-- --spring.profiles.active=seed 로 실행했을 때 생성되는 작업 데이터가 이 계정에 연결되도록 함.
-- 비밀번호는 BCrypt 해시(Spring Security BCryptPasswordEncoder와 100% 호환)이며 평문은 저장되지 않음.
INSERT INTO USERS (USER_ID, USER_PASSWORD, NAME, EMAIL, ROLE, STATUS)
VALUES (
    'testuser',
    '$2b$10$qj9FjOrC8bE3Zubq1jghWO2KOIZ8DVl3najtBxI2FDmnldtQUc.4y',
    '데모 사용자',
    'demo@example.com',
    'USER',
    'ACTIVE'
);

-- 카테고리 1~10 (DemoDataSeeder 및 프론트엔드가 이 ID를 그대로 참조함)
-- CATEGORY_ID는 IDENTITY(GENERATED BY DEFAULT)라 명시적으로 값을 넣어도 됨.
INSERT INTO TASK_CATEGORY (CATEGORY_ID, TITLE, USER_ID) VALUES (1, '개발', 'testuser');
INSERT INTO TASK_CATEGORY (CATEGORY_ID, TITLE, USER_ID) VALUES (2, '운동', 'testuser');
INSERT INTO TASK_CATEGORY (CATEGORY_ID, TITLE, USER_ID) VALUES (3, '회의', 'testuser');
INSERT INTO TASK_CATEGORY (CATEGORY_ID, TITLE, USER_ID) VALUES (4, '문서', 'testuser');
INSERT INTO TASK_CATEGORY (CATEGORY_ID, TITLE, USER_ID) VALUES (5, '테스트', 'testuser');
INSERT INTO TASK_CATEGORY (CATEGORY_ID, TITLE, USER_ID) VALUES (6, '버그', 'testuser');
INSERT INTO TASK_CATEGORY (CATEGORY_ID, TITLE, USER_ID) VALUES (7, '배포', 'testuser');
INSERT INTO TASK_CATEGORY (CATEGORY_ID, TITLE, USER_ID) VALUES (8, '디자인', 'testuser');
INSERT INTO TASK_CATEGORY (CATEGORY_ID, TITLE, USER_ID) VALUES (9, '학습', 'testuser');
INSERT INTO TASK_CATEGORY (CATEGORY_ID, TITLE, USER_ID) VALUES (10, '개인', 'testuser');

COMMIT;
