server:
  port: 18080

spring:
  application:
    name: tracker

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.tracker.tracker
  configuration:
    map-underscore-to-camel-case: true